version: '3.8'

services:
  web:
    build: .
    ports:
      - "8214:80"
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
